
"""Configuration file of MLFlow variables."""

SERVER_URL = ""
PREFIX_EXP_NAME = ""

ROOT_PATH_FROM_SRC = ''
TMP_PATH = ROOT_PATH_FROM_SRC + 'tmp/'

S3_BUCKET = ""
S3_CREDENTIALS_FILENAME = ""

CREDENTIALS_PATH = ROOT_PATH_FROM_SRC + ''
CREDENTIALS_FILENAME = ""
